#!/bin/sh

# Get current date and time
DATE=$(date "+%a %b %d, %I:%M %p ")

# Get system load
LOAD=$(uptime | awk '{print " Load: " $(NF-2) " " $(NF-1) " " $NF}')

# Get available disk space
DISK=$(df -h / | awk '/\// {print " Disk: " $4}')

# Get volume
VOL=$(amixer get Master | awk -F'[][]' 'END{ print $4":"$2 }' | sed 's/on://g')

# Get memory usage
MEMORY=$(free -m | awk '/Mem:/ {print "󰍛 Mem: " $3 "MB / " $2 "MB"}')

# Get IP address
IP=$(ip addr show dev wlp2s0 | awk '/inet / {print "󰖩 IP: " $2}')

# Output the state bar text
echo "$DATE | $LOAD | $DISK | $VOL | $IP"
